# Generated by Django 4.1.7 on 2023-03-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
